services:
  vectordb:
    build:
      context: .
      dockerfile: Dockerfile.vectordb  
    container_name: chroma_docker
    environment:
      - CHROMA_TELEMETRY_ANONYMOUS=false
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://user:hello123@mysql-container:3306/fyp_db
      - CHROMA_LOG_CONFIG=/chromadb/log_config.yml
    networks:
      - my_network
    ports:
      - 8800:8000
    volumes:
      - ./chromadb:/chromadb
      - ./chromadb/log_config.yml:/chromadb/log_config.yml
    depends_on:
      mysql:
        condition:
          service_healthy
    # healthcheck:
    #   test: [ "CMD", "curl", "-f", "http://host.docker.internal:8800/api/v1/heartbeat" ]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: hello123
      MYSQL_DATABASE: fyp_db
    networks:
      - my_network
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  scraper:
    build:
      context: ./
    container_name: scraper
    environment:
     # - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:rootpassword@mysql-container:3306/database

    networks:
      - my_network
    ports:
      - "3001:3001"
    depends_on:
      mysql:
        condition: service_healthy
      # vectordb:
      #     condition: service_healthy

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium-standalone-chrome
    ports:
      - "4444:4444"  # Expose Selenium's default port for remote connection
    networks:
      - my_network
    environment:
      - SE_NODE_MAX_SESSION=5  # Optional: You can set the maximum number of sessions
    volumes:
      - /dev/shm:/dev/shm  # To avoid shared memory issues with Chrome

networks:
  my_network:
    # driver: bridge

volumes:
  mysql_data:
